import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public boolean isPrime(long number) {

		double max = Math.sqrt(number) + 1;

		if (number == 2)
			return true;

		if (number % 2 == 0)
			return false;

		for (long i = 3; i < max; i += 2) {
			if (number % i == 0) {
				return false;
			}
		}
		return true;
	}
	public boolean isPrime2(long number1, long number2) {

		double max1 = Math.sqrt(number1) + 1;
		double max2 = Math.sqrt(number2) + 1;

		if (number1 == 2)
			return true;

		if (number2 == 2)
			return true;

		if (number1 % 2 == 0)
			return false;
		if (number2 % 2 == 0)
			return false;

		for (long i = 3; i < max1; i += 2) {
			if (number1 % i == 0) {
				return false;
			}

			for (long p = 3; p < max2; p += 2) {
				if (number1 % p == 0) {
					return false;
				}
			}

		}
		return true;
	}

   /* public int countNumOfPrime(){
        for (int o = num;o<)
    }
*/



     /*   public static List<Integer> primeFactors ( int number){
            int n = number;
            List<Integer> factors = new ArrayList<Integer>();
            for (int i = 2; i <= n; i++) {
                while (n % i == 0) {
                    factors.add(i);
                    n /= i;
                }
            }
            return factors;
        }*/




	public static void main(String[] args) {

		if (args.length < 1 || args.length > 1) {
			System.out.println("please input a number as the program argument");
			System.exit(0);
		}

		App appObj = new App();
		long input = Long.parseLong(args[0]);

		System.out.println(appObj.isPrime(input));

      /*  System.out.println("Primefactors of 44");
        for (Integer integer : primeFactors(44)) {
            System.out.println(integer);
        }
        System.out.println("Primefactors of 3");
        for (Integer integer : primeFactors(3)) {
            System.out.println(integer);
        }
        System.out.println("Primefactors of 32");
        for (Integer integer : primeFactors(32)) {
            System.out.println(integer);*/
	}
}